### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by khaledkee** [khaledkee/Cunder#2]
Hello there, this the current roadmap of the project:

- [x] torch::Tensor wrapper
- [x] torch::Tensor initialization
- [x] torch::Tensor access
- [x] playground
- [x] unittests
- [x] unittests with doctest instead of acutests
- [x] CLI (github actions)
- [x] torch::jit module load
- [x] torch::Tensor memory management
- [x] torch::jit module run
- [ ] external libraries (torch_scatter, torch_sparse)
- [ ] CMake automatic external library download and remove absolute library path
